<script lang="ts">
	import { enhance } from '$app/forms';
	import Button from '$lib/components/ui/button/button.svelte';

	import type { PageData } from './$types';

	export let data: PageData;
</script>

<h1>Profile</h1>
<p>User id: {data.userId}</p>
<p>username: {data.username}</p>
<p>email: {data.email}</p>
<div class="flex items-center gap-4">
	<p>AI Credits: {data.aiCredits}</p>
	<Button href="/profile/recharge" class="btn variant-filled">Recharge</Button>
</div>
<form method="post" action="?/logout" use:enhance>
	<Button variant="destructive" type="submit">Sign Out</Button>
</form>

<div class="">
	<p>you have saved these images</p>
	<div class="w-full flex flex-wrap gap-4 items-center">
		{#each data.savedImages as image}
			<img class="h-96 w-auto" src={image.url} alt="generated by an ai" />
		{/each}
	</div>
</div>
