<script lang="ts">
	import { enhance } from '$app/forms';

	import type { PageData } from './$types';

	export let data: PageData;
</script>

<h1>Profile</h1>
<p>User id: {data.userId}</p>
<p>username: {data.username}</p>
<p>email: {data.email}</p>
<p>AI Credits: {data.aiCredits}</p>
<form method="post" action="?/logout" use:enhance>
	<button class="btn variant-filled-error" type="submit">Sign Out</button>
</form>

<form action="?/recharge" method="post" use:enhance>
	<button type="submit">Recharge</button>
</form>

<div class="">
	<p>you have saved these images</p>
	<div class="w-full flex flex-wrap gap-4 items-center">
		{#each data.savedImages as image}
			<img class="h-96 w-auto" src={image.url} alt="generated by an ai" />
		{/each}
	</div>
</div>
