name: Run test suite

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        php: [8.3]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: json, dom, curl, libxml, mbstring
          coverage: none

      - name: Configure Flux authentication
        env:
          FLUX_USERNAME: ${{ secrets.FLUX_USERNAME }}
          FLUX_LICENSE_KEY: ${{ secrets.FLUX_LICENSE_KEY }}
        run: composer config http-basic.composer.fluxui.dev "${FLUX_USERNAME}" "${FLUX_LICENSE_KEY}"

      - name: Install Dependencies
        run: composer install --no-progress --no-suggest

      - name: Run Pest
        run: php artisan test
